import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const ralewaySans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Learntern",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ralewaySans.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
