
services:
  # Backend Service (PHP/Laravel)
  app:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: learntern-backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
    depends_on:
      - db

  # Frontend Service (Node.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: learntern-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost/api
    networks:
      - laravel-network
    depends_on:
      - app

  # Web Server (Nginx)
  webserver:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/docker/supervisord.conf:/etc/supervisord.conf
    networks:
      - laravel-network
    depends_on:
      - app
      - frontend

  # Database (MySQL)
  db:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: Learntern
      MYSQL_ROOT_PASSWORD: samaya
      MYSQL_USER: learntern_user
      MYSQL_PASSWORD: samaya
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  dbdata:
    driver: local

networks:
  laravel-network:
    driver: bridge
